### ISSUE TITLE
SEO optimisation and social media tags

### ISSUE THREAD

**Issue by ScottBGI** [gigascience/gigablog#4]
To improve discoverability and shareability of the blog posts we need to add plugins for SEO optimisation, twitter cards and facebook open graph tags. See:

https://developers.facebook.com/docs/sharing/opengraph
https://davidwalsh.name/facebook-meta-tags

https://dev.twitter.com/cards/overview
https://davidwalsh.name/twitter-cards

There are lots of good plugins in wordpress for these such as Yeost:

https://yoast.com/

Installing hit counters to judge traffice would also be very useful.

**Comment by pli888** [comment]
The Yoast SEO plugin was installed on [GigaBlog](http://gigasciencejournal.com/blog/) in March 2018.
